language: node_js

# node_js: # not needed - `.nvmrc` at root-level

cache:
  yarn: true
  directories:
    - "node_modules"

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload

script:
  - yarn lint
  - yarn test:ci
  - yarn build

before_deploy: yarn add now # Install Now CLI

deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: yarn export && now --local-config "./now.preview.json" --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --local-config "./now.master.json" --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
